// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://elevenleads.com.br/terms",
        "contact": {
            "name": "Suporte Eleven Experts",
            "email": "suporte@elevenexperts.com.br"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/leads": {
            "post": {
                "description": "Recebe os dados de um lead e salva no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leads"
                ],
                "summary": "Cria um novo lead",
                "parameters": [
                    {
                        "description": "Dados do Lead",
                        "name": "lead",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/lead.Lead"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "erro de validação",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lead.Lead": {
            "type": "object",
            "properties": {
                "criado_em": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "marcelo@email.com"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string",
                    "example": "Marcelo Oliveira"
                },
                "origem": {
                    "type": "string",
                    "example": "LandingPage"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Eleven Leads API",
	Description:      "API para captação de leads do projeto ELEVEN LEADS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
